### ISSUE TITLE
invalid conversion from const* void to void* warning when using DEBUG_ASSERT with message

### ISSUE THREAD

**Issue by Manu343726** [foonathan/debug_assert#16] opened 2018-12-18 14:35 UTC
Debian Linux GCC 8.1 C++11 ABI with -Wall -pedantic, debug_assert 1.3.3 (from conan). If I do a plain assert like this:

``` cpp
DEBUG_ASSERT(<condition>, assert_handler{});
```

it works, but whenever I add an error message:

``` cpp
DEBUG_ASSERT(<condition>, assert_handler{}, "my custom message");
```
I get a warning about a void* conversion:

```
/home/manuel/.conan/data/debug_assert/1.3.3/Manu343726/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/debug_assert.hpp:279:65: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
                                      || noexcept(Handler::handle(loc, expression, detail::forward<Args>(args)...)))                                             
                                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                 
```

**Comment by Manu343726** [comment] 2018-12-18 14:38
I could try to fix it myself this weekend.

**Comment by foonathan** [comment] 2018-12-18 15:44
What is your `assert_handler`?

**Comment by Manu343726** [comment] 2018-12-18 19:15
A default assert handler, like this one https://gitlab.com/Manu343726/tinyrefl/blob/jinja2-based-tool/tool/include/tinyrefl/tool/detail/assert.hpp

**Comment by foonathan** [comment] 2018-12-18 19:46
Then that's an odd error.

**Comment by foonathan** [comment] 2019-02-12 15:42
Closing as I can't reproduce.

Maybe the error is in the condition?

**Closed as completed by foonathan** 2019-02-12 15:42 UTC
